### ISSUE TITLE
new feature plea from visually impaired user

### ISSUE THREAD

**Issue by JanuszChmiel** [tiagoefmoraes/delphi-twain#2]
Dear experts. I do not see at all and I have A big dream. Does somebody of us think, that it would be possible to add new procedure or function, which would allow to scan image by using USB flatbed scanner by using Black and whyte paper type and procedure should use autobrightness and autocontrast while scanning in real time at The same time? FInereader, Complex C app calls Twain to automatically adjust brightness when scanning by using black and whyte. But what about if somebody very advanced of us would try to invent new revolutionar routine, which would allow to scan by using auto brightness and auto contrast at The same time? HDoes somebody of us think, that it is technically possible to use automatic solution which would change brightness and contrast values when scanner head flow from up to down under The scanning glass? Or only brightness can be controlled and contrast and brightness can not be automatically controlled to get The optimal result? Where I could find some mathematical formulas, which could be used to automatically adapt contrast and brightness values while scanning to get very smart input picture quality from The scanner?
It would be a big revolution when converting paper document to textual form by using OCR software.
What do you think about my dream?

**Comment by tiagoefmoraes** [comment]
@JanuszChmiel Your idea sounds great. 
Unfortunately I'm not working with Delphi anymore and don't know if there is a version of this library that is still being maintained.
Good luck searching for it.
